version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" 
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "bincode"
        update_types: [ "version-update:semver-major" ]
